[theme]
# Azul corporativo MRES para botones y acentos
primaryColor = "#054D7F"

# Fondo blanco puro para facilitar la lectura de cálculos
backgroundColor = "#FFFFFF"

# Gris muy tenue para los widgets (inputs) y la barra lateral
secondaryBackgroundColor = "#F8F9FB"

# Texto negro puro (necesario para el CSS que inyectaste)
textColor = "#000000"

# Fuente profesional
font = "sans serif"

[server]
# Optimización de rendimiento para 2026
headless = true
port = 8501
enableCORS = false
# Evita que el navegador intente descargar archivos estáticos innecesarios
enableStaticServing = true

[browser]
# Desactiva el menú "Gnomo" de Streamlit para una apariencia más limpia de App de ingeniería
gatherUsageStats = false
toolbarMode = "minimal"

[client]
# Muestra el botón de "Download" de forma más prominente
showSidebarNavigation = true
